name: ALLOW
favicon: null
layout_spectrum: 0.8263036017306149
typography_spectrum: 0.9746526170056313
title: '#1 Amazon Best Seller & International Best Seller'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8251358768902719
  lightness: 0.9504066824447364
  saturation: 0.7737158569507301
  rhythmicContrast: 0.3072633044794202
purpose: []
