name: ALLOW
favicon: null
layout_spectrum: 0.99916
typography_spectrum: 0.50335
title: '#1 Amazon Best Seller & International Best Seller'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0045ba'
    - '#ffffff'
    - '#4c90ff'
    - '#000000'
    - '#e53a33'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
